version: 0.1
phases:
  build:
    commands:
      - echo "**** Starting build"
      - echo "**** Checking Jupyter setup"
      - jupyter -h
#      - cd tests ; pytest -v -s -W ignore::DeprecationWarning