version: 0.1
phases:
#  install:
#    commands:
#      - echo "**** Starting install"
#      - wget -q https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
#      - apt-get update
#      - apt-get install unzip -y
#      - unzip ngrok-stable-linux-amd64.zip
      #- pip install qgrid pandas_datareader
      #- jupyter nbextension enable --py --sys-prefix qgrid
      #- jupyter nbextension enable --py --sys-prefix widgetsnbextension
      #- set
      #- pip install jupyterlab
  build:
#    run-as: jovyan
#      # run-as: jovyan <- command is working so for now use --allow-root
    commands:
      - echo "**** Starting build (i.e. run workflow)"
      #- pwd
      #- ls -la /
      #- ls -la /home/jovyan
      - /home/jovyan/ngrok http --log stdout 8888 &
      - cd notebooks; jupyter notebook --allow-root